// Verbatim content transcription from "The Gospel Foundation — Four New
// Modules for the Core Curriculum" PDF. No paraphrasing, no invented
// Scripture references, no invented questions/assignments — every field
// below is copied directly from the supplied document.

export const CURRICULUM = {
  title: "The Gospel & Salvation",
  description: "Discover the good news of Jesus Christ, understand why we need a Savior, respond to the Gospel, know the assurance of salvation, and understand what it means to begin following Jesus as His disciple.",
};

export const MODULES = [
  {
    title: "Before You Believed",
    description: "Before you can fully appreciate the good news, it helps to understand the bad news it answers. This module tells the honest, biblical story of where every person starts — including you, before you trusted Christ.",
    lessons: [
      {
        title: "Made for Good, Marked by the Fall",
        memoryVerseRef: "Genesis 1:27",
        memoryVerseText: "So God created mankind in his own image, in the image of God he created them; male and female he created them.",
        estimatedMinutes: 16,
        sections: [
          { title: "You Were Made on Purpose", content: "The Bible does not begin with sin — it begins with goodness. Genesis 1 describes God creating the world and calling it “very good,” and creating human beings in His own image, meaning every person carries real dignity, real worth, and a real capacity to know and reflect God. Whatever else is true about you, this comes first: you were not an accident, and you were not made for nothing. You were made on purpose, by a good God, to know Him.\n\nThis matters because it means your value was never something you had to earn. It was given to you before you did anything at all — good or bad." },
          { title: "What Went Wrong", content: "Genesis 3 tells the story of the fall — the first humans choosing to distrust God and go their own way. This was not a small mistake. It was a genuine rebellion, a decision to reject God’s good rule and grab for something else. And the consequences were not limited to that first couple. Every person born after them inherited this same, broken condition — a heart bent away from God rather than toward Him.\n\nThis is why the world looks the way it does. The beauty of Genesis 1 and the brokenness we see every day both come from the same true story — good creation, real fall." },
          { title: "Sin Is Not Just “Bad Behavior”", content: "Many people think of sin as simply breaking rules — lying, stealing, losing your temper. Those are real examples of sin, but sin itself is deeper than any single action. At its root, sin is a relational problem: choosing yourself over God, again and again, in ways big and small. It’s less like a stain that needs washing and more like a broken relationship that needs restoring.\n\nThis is important to understand early, because if sin is only about behavior, the solution would just be better behavior. But if sin is about a broken relationship with God, the solution has to be something that actually restores that relationship — which is exactly what this whole module is building toward." },
          { title: "This Is Everyone’s Story, Including Yours", content: "“For all have sinned and fall short of the glory of God” (Romans 3:23). Notice the word “all.” Not just especially bad people. Not just people who never went to church. Everyone — including people who think of themselves as good, kind, and decent. This isn’t said to shame you. It’s said so you can be honest about where you actually started, instead of assuming you were somehow the exception.\n\nBeing honest about this now is what will make the good news in the next module feel like actual good news, instead of a vague, forgettable phrase." },
        ],
        reflectionQuestions: [
          "Before reading this lesson, did you think of yourself as someone who genuinely needed rescuing, or just someone who could use some improvement?",
          "How does knowing you were made in God’s image — with real dignity — change how you think about your life before you knew Christ?",
          "What is the difference, in your own words, between sin as “bad behavior” and sin as a “broken relationship”?",
        ],
        prayer: "God, thank You for making me on purpose, with real worth, even before I knew You. Help me be honest about where I actually started, without shame and without excuses, so I can genuinely understand what You have done for me.",
        assignment: "Read Genesis 1:26-31 and Genesis 3 back to back this week. Write two or three sentences describing the contrast between the world God made and the world sin produced.",
      },
      {
        title: "Separated From a Holy God",
        memoryVerseRef: "Isaiah 59:2",
        memoryVerseText: "But your iniquities have separated you from your God; your sins have hidden his face from you, so that he will not hear.",
        estimatedMinutes: 16,
        sections: [
          { title: "Sin Creates Real Distance", content: "Isaiah’s language is personal, not just legal: sin “separates” and “hides” God’s face. This isn’t a courtroom transaction happening far away — it’s a relationship genuinely broken. Think of any relationship you’ve had that fractured through betrayal or dishonesty. The distance you felt wasn’t abstract; it was real, painful, and specific. That’s the closest human picture we have for what sin does between a person and God." },
          { title: "God’s Holiness Is Not Negotiable", content: "“Holy” means set apart, utterly pure, without any mixture of wrong. This isn’t one attribute among many for God — Scripture describes angels covering their faces and crying “holy, holy, holy” three times over (Isaiah 6:3), a way Hebrew emphasizes something as supremely, comprehensively true. Because God is genuinely holy, He cannot simply shrug at sin the way we sometimes shrug at our own failures or someone else’s. A God who ignored evil would not actually be good." },
          { title: "Under Judgment, Not Just Disappointment", content: "Jesus said plainly that “whoever does not believe stands condemned already” and that “God’s wrath remains on them” (John 3:18, 36). Not eventually — currently. This is sobering, and it’s meant to be. It means the situation before Christ isn’t merely that God is disappointed in us, waiting patiently for us to do better. It’s that a real, serious verdict is already in place, and it requires a real, serious solution — not a small one." },
          { title: "This Is Not Meant to Crush You", content: "If this lesson feels heavy, that’s appropriate — but it isn’t meant to leave you in despair. Scripture is honest about the diagnosis specifically so the cure can be genuinely understood and genuinely appreciated. A doctor who minimizes a serious illness isn’t being kind; they’re being careless. God tells you the truth about your condition because He is about to tell you, in the next module, exactly what He has done about it." },
        ],
        reflectionQuestions: [
          "Has there been a relationship in your life where you experienced this kind of real, painful distance? How does that help you understand what this lesson describes?",
          "Why do you think it matters that God’s holiness means He cannot simply overlook sin?",
          "How do you feel after this lesson — honestly? Discouraged, sober, hopeful, something else?",
        ],
        prayer: "Lord, help me take this honestly, without minimizing it and without despairing over it. Thank You that this isn’t the end of the story — prepare my heart for what comes next.",
        assignment: "Read Isaiah 59:1-2 and John 3:16-18 together this week. Notice how both the seriousness of the problem and the promise of a solution appear side by side.",
      },
      {
        title: "Why You Could Not Save Yourself",
        memoryVerseRef: "Ephesians 2:8-9",
        memoryVerseText: "For it is by grace you have been saved, through faith — and this is not from yourselves, it is the gift of God — not by works, so that no one can boast.",
        estimatedMinutes: 16,
        sections: [
          { title: "The Problem With “Try Harder”", content: "Most people’s default plan for dealing with their own wrongdoing is simple: try to do better. Be kinder. Break the bad habit. Show up more consistently. These efforts aren’t worthless — but they cannot solve the problem Lessons 1.1 and 1.2 described, because that problem isn’t primarily about behavior. It’s about a broken relationship and a real verdict already in place. No amount of future good behavior can undo a past debt or repair a broken trust on its own." },
          { title: "Religion Without Rescue", content: "Jesus once criticized people who “honor me with their lips, but their heart is far from me” (Matthew 15:8). It’s possible to attend every religious service, follow every rule, and still never actually be reconciled to God — because religious activity, on its own, doesn’t reach the actual, relational problem. This isn’t said to discourage genuine faith practices, but to be honest that activity alone was never going to be enough." },
          { title: "A Debt You Could Never Repay", content: "Imagine owing a debt so large that your entire lifetime of income couldn’t cover even the interest. That’s the picture Scripture paints of humanity’s situation before God — not because God is unreasonable, but because the offense of turning away from an infinitely good God carries real, serious weight. No amount of “trying harder” going forward touches a debt already accumulated in the past." },
          { title: "You Needed Someone Outside Yourself", content: "If you cannot pay a debt yourself, the only way forward is for someone else to pay it on your behalf. This is exactly the shape of the good news the next module explores in detail. You could not save yourself — not because you didn’t try hard enough, but because the problem was never something effort alone could fix. That’s actually good news in disguise: it means the solution was never up to you in the first place." },
        ],
        reflectionQuestions: [
          "Before this lesson, did you believe — even a little — that being a genuinely good person would be enough to make things right with God?",
          "Have you ever experienced religious activity without a genuine, felt relationship with God? What was that like?",
          "How does understanding that you needed outside help, not more effort, change how you think about your own story?",
        ],
        prayer: "God, I confess that I’ve often relied on my own effort to feel right with You. Thank You that the solution was never up to me alone. Prepare my heart to receive what You have actually done.",
        assignment: "Write down, honestly, one thing you have relied on in the past to feel “good enough” — being kinder than someone else, going to church, avoiding the worst sins. Bring this to your next session to discuss.",
      },
      {
        title: "God Never Stopped Pursuing You",
        memoryVerseRef: "Romans 5:8",
        memoryVerseText: "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.",
        estimatedMinutes: 16,
        sections: [
          { title: "Common Grace: Kindness You Didn’t Earn", content: "Jesus said God “causes his sun to rise on the evil and the good, and sends rain on the righteous and the unrighteous” (Matthew 5:45). Long before anyone trusts Christ, they are already living inside God’s ongoing kindness — sunlight, breath, beauty, relationships, the ability to enjoy a meal or a friendship. Theologians call this common grace: real goodness from God, given to everyone, not yet the same as the saving grace that reconciles a person to Him, but genuine evidence of His patient, generous character all the same." },
          { title: "Creation Itself Was Pointing to Him", content: "“The heavens declare the glory of God” (Psalm 19:1). Before anyone ever hears the gospel in words, creation itself has already been quietly testifying — through its order, beauty, and vastness — that something, or Someone, greater is behind it all. This doesn’t provide the specific, saving message the next module explores, but it means no one is entirely without witness. God has been leaving clues everywhere, the whole time." },
          { title: "The Quiet Work of Conviction", content: "Jesus promised that the Holy Spirit would “convict the world concerning sin and righteousness and judgment” (John 16:8). That inner sense — sometimes uncomfortable — that something is wrong, or that you’re missing something significant, is not random. It is often the Spirit’s own quiet, patient work, going on before a person ever consciously turns toward God. If you’ve ever felt this, even before you believed, that wasn’t coincidence." },
          { title: "Grace Arrived Before You Ever Turned Around", content: "Here is the sentence that changes everything: Christ died “while we were still sinners” — not after we cleaned ourselves up, not once we deserved it, but before any of that. This is the hinge this entire module has been building toward. The next module tells you exactly what God did about the situation described in these first four lessons. It’s time to look at the actual good news." },
        ],
        reflectionQuestions: [
          "Can you identify a specific way God’s kindness — common grace — was present in your life before you trusted Him?",
          "Has creation itself ever pointed you toward God — a sunset, the night sky, the birth of a child, something else?",
          "Have you ever felt that quiet, inner sense of conviction this lesson describes, even before you understood what it was?",
        ],
        prayer: "Thank You, God, for pursuing me long before I ever turned toward You. Thank You for the kindness, the creation, and the quiet conviction that were all part of bringing me here. Open my heart now to fully understand what You have done.",
        assignment: "Look back over your own life and identify three specific moments — big or small — where you can now see God’s patient pursuit at work before you ever believed. Write these down and share one with your peer guide.",
      },
    ],
  },
  {
    title: "The Gospel — Who Jesus Is and What He Did",
    description: "The actual good news, stated plainly and then explored in depth: who Jesus genuinely is, why He died, why the resurrection matters, and what it means that He now reigns as Lord.",
    lessons: [
      {
        title: "The Good News, Simply Stated",
        memoryVerseRef: "1 Corinthians 15:3-4",
        memoryVerseText: "That Christ died for our sins according to the Scriptures, that he was buried, that he was raised on the third day according to the Scriptures.",
        estimatedMinutes: 15,
        sections: [
          { title: "Four Words That Tell the Whole Story", content: "The Bible’s entire message can be summarized in four words: Creation, Fall, Redemption, Restoration. God made a good world (Creation). Humanity rebelled and broke it (Fall — Module 1’s territory). God acted decisively to rescue and restore His people through Christ (Redemption — what this module explores). And one day, He will make all things new again (Restoration — a promise later modules will unpack). Keeping this whole arc in view helps every individual lesson make sense within the bigger picture." },
          { title: "Not Advice. An Announcement.", content: "The word “gospel” literally means “good news” — like the ancient announcement of a battle already won, not a set of instructions for winning one yourself. This distinction matters enormously. The gospel isn’t primarily a to-do list (“be kinder, pray more, go to church”); it’s news about something God has already, decisively accomplished on your behalf. Everything that follows in this module explains exactly what that accomplished news actually is." },
          { title: "The Message in One Sentence", content: "Paul summarized it this way: Christ died for our sins, was buried, and was raised on the third day — all “according to the Scriptures,” meaning this fulfilled what God had promised long in advance. Three simple, historical claims: a real death, a real burial, a real resurrection. Every lesson in the rest of this module unpacks one part of this single, central sentence." },
          { title: "Why This Changes Everything", content: "If this actually happened — and this course will give you real reason to believe it did — then everything changes. The debt from Module 1 has been paid. The separation has been bridged. The judgment has been satisfied. Not through your effort, but through this. The next four lessons slow down to look closely at who Jesus actually is and what each part of this accomplished, historical rescue genuinely means." },
        ],
        reflectionQuestions: [
          "Before this lesson, did you think of the gospel more as good news to receive or good advice to follow?",
          "How does seeing the whole Bible’s story as Creation, Fall, Redemption, Restoration help you understand where this lesson fits?",
          "What questions do you already have about the claims in 1 Corinthians 15:3-4 that you hope this module will answer?",
        ],
        prayer: "God, thank You for this good news. Help me receive it as an announcement of what You have already done, not one more thing I have to accomplish myself. Open my mind and heart to understand it fully.",
        assignment: "Memorize 1 Corinthians 15:3-4 this week. Practice saying it in your own words to a friend, family member, or your peer guide.",
      },
      {
        title: "Fully God, Fully Man",
        memoryVerseRef: "John 1:14",
        memoryVerseText: "The Word became flesh and made his dwelling among us.",
        estimatedMinutes: 17,
        sections: [
          { title: "Why Jesus Had to Be Genuinely Human", content: "For Jesus’s death to genuinely count for humanity, He had to actually, fully belong to humanity. A substitute has to be one of us — otherwise nothing would actually have been exchanged. Scripture is emphatic that Jesus was genuinely human: He got hungry, tired, and thirsty; He wept; He was tempted “in every way, just as we are — yet he did not sin” (Hebrews 4:15). This wasn’t Him pretending to be human. He genuinely was." },
          { title: "Why Jesus Had to Be Genuinely God", content: "At the same time, only God Himself could pay a debt this large or satisfy a judgment this serious. A merely human sacrifice, however good, could only ever cover one other human’s debt — never the debt of the entire world. John opens his gospel by calling Jesus “the Word,” who “was God” and through whom “all things were made” (John 1:1-3). Jesus’s own claims back this up — He said, “before Abraham was born, I am!” (John 8:58), deliberately using God’s own covenant name for Himself." },
          { title: "Not Half and Half — Both, Completely", content: "This is where many people get confused: Jesus wasn’t half God and half man, like some kind of hybrid. Christians have always confessed that He is completely, fully both at once — one person with two complete natures. This is genuinely mysterious, and no illustration captures it perfectly. But it’s not a contradiction; it’s a truth bigger than ordinary human categories, which is exactly what you’d expect if it’s actually, truly describing God entering His own creation." },
          { title: "The God Who Came Close", content: "“The Word became flesh and made his dwelling among us” — that phrase in the original language literally means He “pitched His tent” among us, the same way God’s presence once dwelt in a tent in the wilderness with Israel. This is the astonishing center of Christianity: God did not stay distant. He came close, took on a genuine human body, and lived among the very people He came to rescue." },
        ],
        reflectionQuestions: [
          "Why does it matter that Jesus was genuinely, fully human — not just appearing to be?",
          "Why does it matter that Jesus was genuinely, fully God — not just an especially good man?",
          "What does it mean to you personally that God chose to “come close” rather than staying distant?",
        ],
        prayer: "Jesus, thank You for genuinely becoming one of us while remaining fully God. Help me hold both truths together, even when I can’t fully explain the mystery, and to worship You rightly because of who You truly are.",
        assignment: "Read John 1:1-14 slowly this week. Underline or write down every phrase that emphasizes Jesus’s deity, and every phrase that emphasizes His genuine humanity.",
      },
      {
        title: "Why He Had to Die",
        memoryVerseRef: "1 Peter 2:24",
        memoryVerseText: "He himself bore our sins in his body on the cross, so that we might die to sins and live for righteousness; by his wounds you have been healed.",
        estimatedMinutes: 18,
        sections: [
          { title: "A Real Exchange, Not Just an Example", content: "It’s tempting to think of the cross mainly as a moving example of sacrificial love — and it is that. But Scripture describes something more specific and concrete: an actual exchange. Peter says Christ “bore our sins” in His own body — meaning the guilt, penalty, and consequence that were genuinely, specifically ours were genuinely, specifically transferred onto Him. This is what theologians call substitution: He took our place." },
          { title: "The Wrath That Was Actually Ours", content: "Remember Module 1’s honest diagnosis: real judgment, real separation, a real and serious debt. The cross is where that judgment actually landed — not on us, but on Christ, who willingly bore it. This is why Jesus’s cry from the cross, quoting Psalm 22 — “My God, my God, why have you forsaken me?” — is so significant. In that moment, He experienced the genuine weight of separation from the Father that our sin deserved, so that we would never have to." },
          { title: "Why Blood? Why a Cross?", content: "Throughout the Old Testament, God established a sacrificial system — animals offered in the place of the guilty, their blood signifying a life given so another life could be spared. This entire system was preparing God’s people to recognize the true, final sacrifice when He came. “Without the shedding of blood there is no forgiveness” (Hebrews 9:22). Jesus is described as the true “Lamb of God” (John 1:29) — every earlier sacrifice was a signpost pointing toward this one, sufficient, final offering." },
          { title: "Paid in Full", content: "Just before He died, Jesus said one word from the cross: “It is finished” (John 19:30). In the original language, this was the same phrase used on a paid receipt — meaning “debt fully discharged.” Not partially paid. Not a down payment requiring your own future installments. Finished. This single word is worth sitting with slowly, because it directly answers Module 1’s honest question: how could a debt this large ever actually be paid?" },
        ],
        reflectionQuestions: [
          "How does understanding the cross as an actual, specific exchange — not just an example of love — change how you think about it?",
          "Why do you think God established the sacrificial system in the Old Testament before Jesus ever came?",
          "What does the word “finished” mean to you personally, considering the debt Module 1 described?",
        ],
        prayer: "Jesus, thank You for genuinely bearing what was actually, specifically mine to bear. I don’t fully understand the depth of what happened at the cross, but I receive it with genuine gratitude. Thank You that it is finished.",
        assignment: "Read Isaiah 53 in full this week — written roughly 700 years before Jesus was born. Circle every phrase that describes what would happen to Him.",
      },
      {
        title: "He Did Not Stay Dead",
        memoryVerseRef: "1 Corinthians 15:20",
        memoryVerseText: "But Christ has indeed been raised from the dead, the firstfruits of those who have fallen asleep.",
        estimatedMinutes: 16,
        sections: [
          { title: "This Actually Happened", content: "The resurrection is not a metaphor, a symbol, or a comforting story regardless of whether it’s literally true. The New Testament presents it as a real, historical, bodily event — Jesus was genuinely dead, and then genuinely, physically alive again. He was seen, touched, and eaten meals with by hundreds of witnesses over forty days (1 Corinthians 15:5-7), many of whom were still alive when this was written and could have been questioned directly." },
          { title: "Proof the Payment Was Accepted", content: "If the cross was where the debt was paid, the resurrection is the receipt proving it was accepted. Paul says Jesus “was delivered over to death for our sins and was raised to life for our justification” (Romans 4:25) — meaning the resurrection isn’t a separate, bonus miracle tacked onto the story. It’s the actual, necessary proof that the Father accepted the Son’s sacrifice as sufficient. Without it, we would have no way of knowing the payment actually worked." },
          { title: "Firstfruits: A Promise for You Too", content: "Paul calls Christ’s resurrection the “firstfruits” — the first part of a harvest, guaranteeing the rest is genuinely coming. This means Jesus’s resurrection isn’t just something that happened to Him alone; it establishes the actual pattern for what will eventually happen to every believer. Your own future, bodily resurrection is not wishful thinking — it follows the same, guaranteed pattern already demonstrated in Christ." },
          { title: "A Faith You Can Investigate", content: "Christianity doesn’t ask you to believe something with no basis. It makes a historical claim, backed by named witnesses, a specific timeframe, and a movement that changed the ancient world within a generation — all beginning with people who were, by their own accounts, initially skeptical themselves. You are welcome, even encouraged, to look further into the historical case for the resurrection. This faith was never meant to require you to switch off your mind." },
        ],
        reflectionQuestions: [
          "Had you previously thought about the resurrection as a historical claim you could actually investigate, or mainly as a symbolic story?",
          "Why does the resurrection function as “proof,” not just a happy ending, according to this lesson?",
          "What hope does the idea of “firstfruits” give you regarding your own future?",
        ],
        prayer: "Thank You, Jesus, that You did not stay dead. Thank You that Your resurrection is real, historical proof that the payment for my sin was genuinely accepted. Build my confidence in this truth as I continue learning.",
        assignment: "Read 1 Corinthians 15:1-8 and list every specific detail Paul gives — names, numbers, timing — that makes this claim historically testable rather than vague.",
      },
      {
        title: "Jesus Is Lord, Now and Forever",
        memoryVerseRef: "Philippians 2:9-10",
        memoryVerseText: "Therefore God exalted him to the highest place and gave him the name that is above every name, that at the name of Jesus every knee should bow.",
        estimatedMinutes: 16,
        sections: [
          { title: "He Is Reigning Right Now", content: "After the resurrection, Jesus ascended to heaven and “sat down at the right hand of God” (Mark 16:19) — a position of active, ongoing authority, not passive retirement. He is not merely a historical figure to admire from a distance; He is presently, actively reigning over all creation right now, including over whatever specific circumstances you are currently facing." },
          { title: "More Than Savior — Also Lord", content: "It’s possible to want Jesus as a rescuer from consequences while resisting Him as an authority over daily life. But Scripture consistently presents both together: “if you declare with your mouth, ‘Jesus is Lord’… you will be saved” (Romans 10:9). Genuine faith includes genuine submission — not because God demands blind obedience, but because trusting someone as your rescuer naturally means trusting their direction for your life as well." },
          { title: "He Is Coming Back", content: "The story doesn’t end with the ascension. Scripture promises Jesus will return visibly, decisively, and universally — “every eye will see him” (Revelation 1:7). This future hope isn’t meant to produce anxiety; it’s meant to produce genuine motivation and confidence, knowing this present, sometimes-difficult chapter of history is not the final chapter." },
          { title: "What This Means for How You Live", content: "If Jesus genuinely reigns now, and is genuinely coming again, this reshapes how you approach today. Present difficulty is real but temporary. Present obedience matters and is never wasted. You are not following a distant historical figure or a set of old ideas — you are in relationship with a living, reigning King who is actively present and actively coming back. The next module explores what your actual response to all of this should look like." },
        ],
        reflectionQuestions: [
          "Have you tended to think of Jesus mainly as a past historical figure, or as a presently reigning King?",
          "What does it mean to you that trusting Jesus as Savior also means submitting to Him as Lord?",
          "How does knowing He is coming back shape how you think about your life right now?",
        ],
        prayer: "Jesus, I confess You as both Savior and Lord. Thank You that You reign right now, and that You are coming back. Help me live today in light of both realities.",
        assignment: "Read Philippians 2:5-11 and Revelation 1:7 this week. Write a short paragraph describing what it means to you that Jesus both reigns now and will visibly return.",
      },
    ],
  },
  {
    title: "Responding to the Gospel and Knowing You're Saved",
    description: "Understanding the gospel is not the same as responding to it. This module walks through what genuine repentance and faith actually involve, and how you can know — with real confidence — that your salvation is genuine.",
    lessons: [
      {
        title: "Repentance: Turning Toward God",
        memoryVerseRef: "Acts 3:19",
        memoryVerseText: "Repent, then, and turn to God, so that your sins may be wiped out.",
        estimatedMinutes: 16,
        sections: [
          { title: "More Than Feeling Sorry", content: "Repentance is often reduced to simply feeling bad about something — but biblical repentance is bigger than a feeling. It’s an actual change of direction, described by Peter as “turning to God” so sins are genuinely dealt with. You can feel sorry about something for years and never actually turn away from it. Repentance means the turning genuinely happens, not just the feeling." },
          { title: "Turning Toward, Not Just Away", content: "Notice repentance is described as turning toward God, not merely away from bad behavior. This is a crucial, often-missed distinction. Repentance is fundamentally relational — it’s about realigning your whole life toward God as the center, not just crossing items off a list of things to stop doing. The behavior change that follows genuine repentance is real, but it flows out of this deeper, relational turning, not the other way around." },
          { title: "Godly Sorrow vs. Worldly Sorrow", content: "Paul draws a sharp distinction: “godly sorrow brings repentance that leads to salvation… but worldly sorrow brings death” (2 Corinthians 7:10). Worldly sorrow typically grieves over getting caught or facing consequences. Godly sorrow grieves because sin genuinely offended a God who is genuinely good. It’s worth honestly asking which kind of sorrow you have experienced — and trusting God to grow the first kind in you where it’s still developing." },
          { title: "A Gift You Receive, Not Just a Decision You Make", content: "Here’s something that offers real comfort: Scripture describes repentance itself as something God “grants” (Acts 11:18) — not merely a feat of willpower you have to generate entirely on your own. If you feel like you can’t genuinely change on your own, that’s actually the right starting place. Turn toward God honestly, and trust Him to grant the genuine turning, even as you take the actual step of turning." },
        ],
        reflectionQuestions: [
          "Have you ever confused feeling sorry about something with genuinely turning away from it?",
          "What does “turning toward God,” not just away from behavior, look like for you personally right now?",
          "Does knowing repentance is something God grants, not just something you generate alone, change how you approach it?",
        ],
        prayer: "God, I turn toward You right now, honestly, however imperfectly. Grant me genuine repentance, not just surface-level feeling. Thank You that this turning is something You help me do, not something I have to accomplish entirely on my own.",
        assignment: "Read Acts 3:17-21 and 2 Corinthians 7:8-10 this week. Identify one specific area of your life where you sense God inviting you to turn more fully toward Him.",
      },
      {
        title: "Faith: Trusting Him Completely",
        memoryVerseRef: "Hebrews 11:1",
        memoryVerseText: "Now faith is confidence in what we hope for and assurance about what we do not see.",
        estimatedMinutes: 16,
        sections: [
          { title: "More Than Believing Facts", content: "It’s possible to believe every fact this course has covered — the cross, the resurrection, Jesus’s deity — and still not have saving faith. James points out that “even the demons believe that — and shudder” (James 2:19). Saving faith isn’t merely intellectual agreement; it’s genuine, personal trust — leaning your actual weight on Christ, the way you’d trust a chair to hold you, not just agree the chair exists." },
          { title: "The Object of Faith Matters", content: "Sincerity alone isn’t the point — what (or who) you’re sincere about matters enormously. Scripture is specific: “believe in the Lord Jesus, and you will be saved” (Acts 16:31). Not generic spirituality. Not sincerity regardless of object. Christ specifically, because He specifically is the one who accomplished the rescue this course has described." },
          { title: "Faith Alone, Not Faith Plus", content: "“By grace you have been saved, through faith… not by works” (Ephesians 2:8-9). This means no further requirement needs to be added to genuine faith in Christ — not a certain feeling, not a certain level of moral cleanup beforehand, not a probationary period. Faith alone in Christ alone is genuinely, completely sufficient, because it rests entirely on what He already accomplished, not on what you still need to accomplish." },
          { title: "What Genuine Trust Looks Like", content: "Practically, this trust often looks like an honest, internal shift: stopping the attempt to earn or prove your own worthiness, and instead resting your whole confidence on what Christ has already done. It doesn’t require the absence of every remaining question — even genuine believers continue growing in understanding for the rest of their lives. It requires genuine, personal reliance, starting now, even while questions continue to be worked through." },
        ],
        reflectionQuestions: [
          "Is there a difference, in your own experience, between believing facts about Jesus and actually trusting Him personally?",
          "Why does it matter that faith’s object is specifically Christ, not just sincerity in general?",
          "What would it look like, practically, for you to rest your confidence on Christ rather than your own effort?",
        ],
        prayer: "Jesus, I place my trust in You specifically — not in my own effort, not in vague spirituality, but in You. Help my faith grow into genuine, personal reliance, even as I continue learning and understanding more.",
        assignment: "Read Hebrews 11:1-6 and Ephesians 2:8-9 this week. Write a short, honest description of where your own faith currently stands — genuine trust, still forming, somewhere in between.",
      },
      {
        title: "Confessing Christ and Counting the Cost",
        memoryVerseRef: "Romans 10:9",
        memoryVerseText: "If you declare with your mouth, ‘Jesus is Lord,’ and believe in your heart that God raised him from the dead, you will be saved.",
        estimatedMinutes: 16,
        sections: [
          { title: "Saying It Out Loud", content: "Paul pairs believing in the heart with confessing “with your mouth” — an actual, spoken, outward declaration. Genuine faith doesn’t stay entirely private and hidden; it finds expression. This doesn’t require a formal, dramatic announcement to everyone at once — it might simply mean honestly telling God in prayer, and then telling at least one trusted person, what you now believe." },
          { title: "Surrendering the Wheel", content: "Confessing “Jesus is Lord” is more than a religious phrase — it’s handing over control. Paul describes this as presenting yourself as “a living sacrifice” (Romans 12:1) — an ongoing, daily posture, not a single, one-time transaction. This surrender begins now and continues developing for the rest of your life, one specific area and one specific day at a time." },
          { title: "Jesus Was Honest About the Cost", content: "Jesus never hid that following Him would cost something real. He told people to “count the cost” before building, the way you’d plan before starting construction (Luke 14:28). This might mean changed relationships, changed priorities, or genuine, ongoing struggle. This isn’t mentioned to discourage you — it’s mentioned so your decision is honest and informed, not naive." },
          { title: "Worth It", content: "Whatever this costs, Scripture is confident it’s worth it — “I consider that our present sufferings are not worth comparing with the glory that will be revealed in us” (Romans 8:18). Believers throughout history, having genuinely counted this cost, have consistently testified that following Christ was worth everything it required. This is not a decision you make blindly — it’s one you can make with open, honest eyes." },
        ],
        reflectionQuestions: [
          "Have you told God, and at least one other person, what you now believe? If not, what would that step look like?",
          "What does “surrendering the wheel” to Christ’s lordship look like practically in your own, current life?",
          "What genuine cost have you already faced, or do you anticipate facing, in following Christ?",
        ],
        prayer: "Jesus, I confess You as Lord, not just Savior. I give You control of my life, honestly and imperfectly. Help me count the cost clearly, and trust that following You is genuinely worth it.",
        assignment: "This week, if you have not already done so, tell at least one person you trust about your decision to follow Christ. Write down how that conversation went.",
      },
      {
        title: "How You Can Know You Are Saved",
        memoryVerseRef: "1 John 5:13",
        memoryVerseText: "I write these things to you who believe in the name of the Son of God so that you may know that you have eternal life.",
        estimatedMinutes: 17,
        sections: [
          { title: "Not a Feeling — A Promise", content: "Many new believers assume their confidence should come from a strong, consistent feeling. But John’s stated purpose here is that you may genuinely “know” — not merely hope — and this knowledge is grounded in a written promise, not your own shifting emotions. Feelings fluctuate with sleep, circumstance, and mood. God’s promise does not. This is meant to be your actual, stable foundation." },
          { title: "The Finished Work Behind Your Confidence", content: "Remember the word from Lesson 2.3: “Finished.” Your assurance rests on this completed, historical fact, not on your own, ongoing performance. Hebrews describes believers as “sanctified through the sacrifice of the body of Jesus Christ once for all” (Hebrews 10:10) — a completed event that cannot be undone by your continued imperfection, because it was never dependent on your performance in the first place." },
          { title: "Signs That Something Real Has Changed", content: "Alongside this promise, Scripture also describes genuine, though often gradual, evidence: a new, growing desire for God (2 Corinthians 5:17), a new capacity to love other believers (1 John 3:14), and the Spirit’s own inner witness “that we are God’s children” (Romans 8:16). These evidences don’t replace the promise as your foundation — but they genuinely, meaningfully confirm it." },
          { title: "What to Do With Doubt", content: "Nearly every believer experiences doubt at some point — this doesn’t automatically mean your faith isn’t genuine. When doubt comes, the right response isn’t panic, but return: return to God’s promise, return to the finished work of the cross, return to honest conversation with someone you trust. Doubt honestly examined and brought into the light tends to lose its grip; doubt hidden in isolation tends to grow. You do not walk this road alone." },
        ],
        reflectionQuestions: [
          "Have you based your confidence in your salvation more on your feelings than on God’s stated promise? How does this lesson invite you to shift that?",
          "What genuine evidence of change — however small or gradual — have you noticed in your own life so far?",
          "Who could you talk to honestly the next time you experience doubt, rather than carrying it alone?",
        ],
        prayer: "God, thank You that my salvation rests on Your finished work and Your stated promise, not on my own fluctuating feelings. Help me return to this truth whenever doubt arises, and give me the courage to be honest with someone else when I struggle.",
        assignment: "Read 1 John 5:11-13 and write this promise somewhere you will see it regularly — your phone, a notecard, your journal — as a resource for future moments of doubt. Share with your peer guide how you’re feeling about your own assurance right now, honestly.",
      },
    ],
  },
  {
    title: "From Convert to Disciple",
    description: "Believing in Jesus was the beginning, not the finish line. This module explains what it actually means to follow Him as an ongoing disciple, the habits that will sustain your growth, and why you were never meant to walk this road alone.",
    lessons: [
      {
        title: "What Does It Mean to Follow Jesus as a Disciple, Not Just a Convert?",
        memoryVerseRef: "John 8:31",
        memoryVerseText: "Then Jesus said to those Jews who believed him, ‘If you hold to my teaching, you are really my disciples.’",
        estimatedMinutes: 16,
        sections: [
          { title: "A Convert Believed. A Disciple Follows.", content: "The word “convert” describes a moment — the point where you turned from your old direction and trusted Christ. That moment was real and it matters enormously. But the Bible’s word for what comes next is “disciple,” which literally means a learner, a student who follows a teacher’s actual life and instruction, not just their opening lecture. Jesus said real disciples are the ones who “hold to” His teaching — meaning this is ongoing, not a one-time event. Your conversion was the doorway. Discipleship is the house you now get to live in for the rest of your life." },
          { title: "Jesus’s Actual Commission", content: "Just before returning to heaven, Jesus’s final instruction wasn’t “go make converts.” It was “go and make disciples of all nations… teaching them to obey everything I have commanded” (Matthew 28:19-20). This is the whole reason a network like this one exists — not to collect decisions, but to walk with people, over time, toward genuine, growing obedience and love for Christ. That’s also the whole reason this course keeps going well past the moment you first believed." },
          { title: "Jesus Was Honest: This Would Cost Something", content: "Jesus used deliberately shocking language: “Anyone who comes to me and does not hate father and mother… yes, even their own life — such a person cannot be my disciple” (Luke 14:26). He wasn’t commanding literal hatred of family — Scripture elsewhere clearly commands love and honor toward parents. He was using intentional, culturally-understood overstatement to make one point unmistakably clear: nothing, not even your most precious relationship, gets to outrank Him. Discipleship is genuinely costly, and Jesus never hid that from anyone." },
          { title: "This Is for You, Not Just “Spiritual” People", content: "It’s easy to assume genuine, serious discipleship is for pastors, missionaries, or people who seem unusually devoted — and that your own job is just to believe and attend. But Jesus’s commission was to “all nations,” with no asterisk excluding ordinary people with ordinary lives. Whatever your background, schedule, or personality, this call is genuinely, personally yours. The rest of this module is about what that actually, practically looks like." },
        ],
        reflectionQuestions: [
          "Before this lesson, did you think of your faith mainly as a decision already made, or as an ongoing relationship of learning and following?",
          "How does Jesus’s honesty about cost — in Luke 14:26 — change how you think about what you signed up for?",
          "Have you assumed serious discipleship was for “especially spiritual” people rather than for you, personally? What would it look like to embrace this as genuinely your own calling?",
        ],
        prayer: "Jesus, thank You for saving me — and thank You for calling me to so much more than a single decision. Help me understand what it actually means to follow You as an ongoing disciple, and give me the honesty to count the cost and the courage to pay it.",
        assignment: "Read Matthew 28:18-20 and Luke 14:25-33 this week. Write two or three sentences about what “discipleship, not just conversion” means for your own, specific life right now.",
      },
      {
        title: "The Habits That Will Sustain Your Growth",
        memoryVerseRef: "1 Peter 2:2",
        memoryVerseText: "Like newborn babies, crave pure spiritual milk, so that by it you may grow up in your salvation.",
        estimatedMinutes: 15,
        sections: [
          { title: "Why Habits, Not Just Willpower", content: "Nobody grows spiritually by accident. Peter compares this to a newborn craving milk — an ongoing, repeated need, not a single feeding that lasts a lifetime. The disciples who grow into deep maturity aren’t the ones with the strongest willpower; they’re the ones who build sustainable, repeated habits into their ordinary, daily and weekly rhythm. This lesson previews three of those habits — you’ll go much deeper into each one in dedicated modules later in this course." },
          { title: "Feeding on God’s Word", content: "Regular, personal engagement with Scripture is how you actually hear from God and let your thinking be genuinely reshaped by His. This doesn’t require hours each day — it requires consistency, even in small amounts. You’ll build real, practical skill for this in the module ahead called “The Bible — God’s Word to You.” For now, simply begin: even five honest minutes a day is a genuine start." },
          { title: "A Consistent Life of Prayer", content: "Prayer is simply ongoing, honest conversation with God — gratitude, confusion, need, and everything in between, expressed in your own words. Paul’s instruction to “pray without ceasing” (1 Thessalonians 5:17) describes a woven-throughout-the-day posture, not just a formal, scheduled event. A full module on prayer is coming later in this course. For now, start small: talk to God honestly today, in your own words, about something real." },
          { title: "Committed to a Church Family", content: "Scripture is direct: don’t neglect “meeting together, as some are in the habit of doing” (Hebrews 10:25). Solitary, private faith was never the biblical design — you were saved into a family, not just into a private relationship. A dedicated module on the church is ahead. For now, if you haven’t already, take a concrete step toward consistent involvement in a local church community this week." },
        ],
        reflectionQuestions: [
          "Which of these three habits — Scripture, prayer, church — already feels like a growing part of your life, and which feels hardest to start?",
          "What has typically caused good spiritual habits to fade for you in the past — busyness, discouragement, something else?",
          "What is one small, realistic step you could take this week in the habit that currently feels hardest?",
        ],
        prayer: "God, I want to grow, not just to have made a decision one time. Help me build real, sustainable habits of Scripture, prayer, and church involvement — not out of pressure, but out of genuine desire to know You more.",
        assignment: "Choose one of the three habits in this lesson and take one concrete, specific step in it this week — five minutes of Bible reading, one honest prayer, or one message to a local church about visiting.",
      },
      {
        title: "You Were Never Meant to Grow Alone",
        memoryVerseRef: "Proverbs 27:17",
        memoryVerseText: "As iron sharpens iron, so one person sharpens another.",
        estimatedMinutes: 16,
        sections: [
          { title: "Being Walked With by Someone Further Along", content: "Paul didn’t just teach Timothy from a distance — he called him “my true son in the faith” (1 Timothy 1:2) and invested in him personally, over years, through real relationship. This is exactly the relationship a Peer Guide is meant to offer you within this network — someone genuinely further along, willing to walk with you personally, not just deliver information. If Module 0 introduced you to what a Peer Guide does, this lesson is telling you why that role exists biblically: because no one was ever meant to grow through solitary information alone." },
          { title: "Iron Sharpening Iron: Your Peers Matter Too", content: "Growth doesn’t only happen vertically, through mentors. “As iron sharpens iron, so one person sharpens another” describes mutual friendship — honest relationship with others at a similar stage of the journey, encouraging and correcting each other along the way. As you continue in this network, look for these kinds of peer friendships too, not just mentoring relationships. Both are genuinely, biblically necessary." },
          { title: "One Day, You’ll Walk With Someone Behind You", content: "Paul told Timothy to take what he’d learned and “entrust to reliable people who will also be qualified to teach others” (2 Timothy 2:2) — a chain of discipleship meant to continue across generations. You don’t need to have arrived at complete maturity before this becomes possible. Even relatively new believers can share what they’ve genuinely learned so far with someone just one or two steps behind them. This network’s entire model — peer discipling peer — is built directly on this passage." },
          { title: "This Isn’t an Optional Extra — It’s How Growth Actually Happens", content: "It’s tempting to treat relationship as a nice bonus and private study as the “real” spiritual work. Scripture reverses this: genuine, ongoing relationship — being discipled, and eventually discipling others — is one of the primary, ordinary means God uses to grow His people. If you skip this and try to grow entirely alone, you’re working against the actual design, not just taking a slower path." },
        ],
        reflectionQuestions: [
          "Do you currently have someone further along in faith walking personally with you? If not, what step could you take toward this?",
          "Who in your life could become this kind of “iron sharpening iron” peer friendship — honest, mutual, ongoing?",
          "Even at your current stage of growth, is there someone one or two steps behind you that you could begin encouraging?",
        ],
        prayer: "God, thank You that I was never meant to grow alone. Thank You for the people You’ve placed further along to walk with me, and for peers who can sharpen me. Show me who I might someday walk alongside, even now, in whatever way I genuinely can.",
        assignment: "If you have a Peer Guide, reach out to them this week with one honest question or update about your own growth. If you don’t yet have one, take a step to connect with your Peer Guide or a peer group this week.",
      },
      {
        title: "Committed for the Long Haul",
        memoryVerseRef: "Proverbs 24:16",
        memoryVerseText: "For though the righteous fall seven times, they rise again.",
        estimatedMinutes: 15,
        sections: [
          { title: "Fruit That Actually Remains", content: "Jesus said He chose His disciples to “go and bear fruit — fruit that will last” (John 15:16). Genuine discipleship isn’t measured by a single dramatic moment; it’s measured by a lasting, sustained pattern over time — character genuinely formed, relationships genuinely changed, faith genuinely deepened, year after year. This kind of lasting fruit almost always grows out of the ordinary, sustained habits Lesson 4.2 described, not out of isolated bursts of spiritual intensity." },
          { title: "Setbacks Are Normal, Not Disqualifying", content: "“The righteous fall seven times, and rise again” — not zero times. Even genuinely growing disciples experience real setbacks: seasons of neglecting Scripture, prayer that goes cold, sin that resurfaces. This verse isn’t giving permission to stay down; it’s honest reassurance that falling doesn’t erase your identity as a disciple. What marks a genuine disciple isn’t a flawless record — it’s getting back up, again and again, and continuing forward." },
          { title: "Don’t Face Setbacks Alone", content: "This is exactly where Lesson 4.3’s relationships matter most. A setback faced in isolation and shame tends to grow; a setback brought honestly to a Peer Guide or trusted friend tends to lose its power. If you experience a genuine setback in the weeks or months ahead, resist the instinct to hide — reach out, be honest, and let someone walk you back toward rising again." },
          { title: "A Lifetime, Not a Phase", content: "This module — and this entire gospel foundation you’ve just walked through — isn’t a box to check before moving on to “the real content.” It’s the posture that should shape your entire life: continuing to learn, continuing to build sustaining habits, continuing in relationship, continuing to rise after every fall. The modules ahead in this course will go deep into specific areas of that ongoing life. This is where that lifelong journey genuinely begins." },
        ],
        reflectionQuestions: [
          "Have you already experienced a setback since coming to faith? How did you respond — did you hide it, or bring it to someone honestly?",
          "What would “fruit that remains” look like for you, specifically, five or ten years from now?",
          "As you move into the rest of this course, what is one thing from this entire module you want to carry with you?",
        ],
        prayer: "God, thank You that this is a lifelong journey, not a single event. Help me build lasting fruit, rise after every setback, and never try to walk this road alone. As I move into the rest of this course, keep me genuinely hungry to keep growing.",
        assignment: "Write a short letter to yourself about where you are right now, at the very start of this discipleship journey. Seal it, save it, and revisit it after you complete this entire course.",
      },
    ],
  },
];
