import { Platform } from "react-native";

// Stage 26B — shared, platform-neutral background-call support. Call
// screens (audio.tsx/video.tsx/group.tsx) only ever call these two
// functions; every platform-specific decision lives here, never in a call
// screen. This is intentionally NOT four independent implementations of
// call logic — it is one interface with a thin per-platform branch.
//
// ANDROID: starts/stops a real foreground service (modules/
// call-foreground-service — a local native Expo module; see that
// directory for the Kotlin implementation) so the OS does not suspend the
// process/network while an active call is backgrounded. Confirmed via
// direct source inspection (Stage 26B-A) that neither react-native-agora
// nor any other installed dependency provides this — Android is the one
// platform with no other existing mechanism for this at all.
//
// iOS/iPadOS: nothing to imperatively start here. UIBackgroundModes:
// ["audio"] (declared in app.json) is what grants the OS-level allowance
// to keep running in the background at all for an active audio session;
// Agora's own SDK manages the AVAudioSession once a channel is joined.
// Deliberately NOT "voip" — this app has no CallKit/PushKit integration,
// and declaring voip without one is both against Apple's own guidance for
// that background mode and a real App Store review risk. There is no
// native module to call into for this platform in this stage.
//
// macOS/Windows: confirmed via source inspection that this project has no
// react-native-macos or react-native-windows dependency, no native
// project for either exists or can currently be generated by this Expo/
// EAS setup at all (see the Stage 26B report). These calls are safe
// no-ops here — exactly the same as they already are on any platform
// without a native implementation registered.

type CallBackgroundServiceNativeModule = {
  start(isVideo: boolean): void;
  stop(): void;
};

let nativeModule: CallBackgroundServiceNativeModule | null = null;
if (Platform.OS === "android") {
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const { requireNativeModule } = require("expo-modules-core") as typeof import("expo-modules-core");
    nativeModule = requireNativeModule<CallBackgroundServiceNativeModule>("CallForegroundService");
  } catch (e) {
    // Expected until a build that actually includes the native module
    // (modules/call-foreground-service) has been produced — see the
    // Stage 26B report's IMPLEMENTED-vs-BUILT distinction. Never throws
    // into a call screen for this reason; background support is simply
    // unavailable until then.
    console.warn("callBackgroundSupport: native module unavailable", e instanceof Error ? e.message : String(e));
    nativeModule = null;
  }
}

/**
 * Call once the Agora connection reaches its existing "connected" state —
 * never at screen-open, ring, or connecting time. Safe to call more than
 * once for the same call (the Android service treats a repeat start as an
 * idempotent notification update, not a new instance).
 */
export function startCallBackgroundSupport(isVideo: boolean): void {
  if (Platform.OS === "android") {
    // Android 12+ refuses to start a foreground service while the app is in
    // the background (e.g. the call connects after the user switched away).
    // That costs background survival for this call, never the call itself.
    try {
      nativeModule?.start(isVideo);
    } catch (e) {
      console.warn("callBackgroundSupport: start failed", e instanceof Error ? e.message : String(e));
    }
  }
  // iOS/macOS/Windows: no imperative start step exists/applies (see above).
}

/**
 * Call through the existing call-termination/cleanup path (handleEndCall,
 * handleLeave, and — as a safety net for any exit path that doesn't run
 * either of those, e.g. an unmount that bypasses them — useAgoraEngine's
 * own cleanup). Safe to call repeatedly and safe to call even if start was
 * never called.
 */
export function stopCallBackgroundSupport(): void {
  if (Platform.OS === "android") {
    try {
      nativeModule?.stop();
    } catch (e) {
      console.warn("callBackgroundSupport: stop failed", e instanceof Error ? e.message : String(e));
    }
  }
}
