-- 153: P2P Rooms — Shareable Room Links (Stage B: database + API foundation).
--
-- Purely additive invitation layer over THREE existing, unmodified room
-- domains — zero columns/RLS changed on any of them:
--   p2p_break_rooms, p2p_church_calls, p2p_family_worship_sessions
-- Direct 1:1 calls and Prayer 2.0 gatherings are explicitly deferred (both
-- already have their own complete, differently-shaped invitation/initiation
-- flows — approved decision, not a gap).
--
-- CORE PRINCIPLE (non-negotiable, per spec): "A link is an invitation
-- mechanism, not an authorization bypass." This table stores only enough
-- to resolve WHICH room a link points to and whether the link itself is
-- still valid. The actual join always goes through the existing,
-- untouched join endpoints (/calls/rooms/:id/join,
-- /churches/calls/:id/join, /family/worship/:id/join), which independently
-- re-check real membership/host authorization exactly as they do today.
--
-- Explicit named FK columns (never a polymorphic source_type/source_id
-- pair) — the same convention used throughout this codebase (Kingdom
-- Stories' related_* columns, Kingdom Wins' mission_story_id/etc.).
--
-- TOKEN STORAGE (approved refinement): only sha256(token) is ever stored.
-- The raw token exists only transiently — generated by the API, returned
-- once in the creation response, and never persisted, logged, or returned
-- again by any other endpoint. A database read of this table alone can
-- never yield a usable invitation link.

create table if not exists p2p_room_invitations (
  id                          uuid primary key default gen_random_uuid(),
  token_hash                  text not null unique,

  break_room_id               uuid references p2p_break_rooms(id) on delete cascade,
  church_call_id               uuid references p2p_church_calls(id) on delete cascade,
  family_worship_session_id    uuid references p2p_family_worship_sessions(id) on delete cascade,

  created_by                  uuid references auth.users(id) on delete set null,
  status                      text not null default 'active' check (status in ('active', 'revoked')),
  expires_at                  timestamptz,

  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),
  revoked_at                  timestamptz,

  -- Exactly one room reference per invitation — never zero, never more
  -- than one, and never a generic/ambiguous target.
  check (num_nonnulls(break_room_id, church_call_id, family_worship_session_id) = 1)
);

create index if not exists idx_p2p_room_invitations_created_by on p2p_room_invitations(created_by, created_at desc);

-- ── One ACTIVE invitation per room, enforced by the database itself ───────
-- (approved decision: creating a replacement revokes the previous one).
-- A partial unique index — not just application logic — is what actually
-- makes this safe under concurrent creation requests: two simultaneous
-- "create invitation" calls for the same room can both attempt to INSERT
-- an active row, but only one INSERT can ever succeed; the loser gets a
-- unique-violation the API layer resolves by returning the row that won
-- (see p2p_create_room_invitation() below and routes/roomInvitations.ts).
create unique index if not exists idx_p2p_room_invitations_active_break_room
  on p2p_room_invitations(break_room_id) where status = 'active' and break_room_id is not null;
create unique index if not exists idx_p2p_room_invitations_active_church_call
  on p2p_room_invitations(church_call_id) where status = 'active' and church_call_id is not null;
create unique index if not exists idx_p2p_room_invitations_active_family_worship
  on p2p_room_invitations(family_worship_session_id) where status = 'active' and family_worship_session_id is not null;

-- ── Atomic "revoke old, create new" — one function call, one transaction ──
-- Ownership/authorization is verified by the CALLING route (against the
-- specific room's real host_id) before this is ever invoked — this
-- function's only job is the atomic revoke+insert, not authorization.
create or replace function p2p_create_room_invitation(
  p_room_type   text,
  p_room_id     uuid,
  p_created_by  uuid,
  p_token_hash  text,
  p_expires_at  timestamptz
)
returns p2p_room_invitations
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result p2p_room_invitations;
begin
  if p_room_type = 'break_room' then
    update p2p_room_invitations set status = 'revoked', revoked_at = now(), updated_at = now()
      where break_room_id = p_room_id and status = 'active';
    insert into p2p_room_invitations (token_hash, break_room_id, created_by, expires_at)
      values (p_token_hash, p_room_id, p_created_by, p_expires_at)
      returning * into v_result;
  elsif p_room_type = 'church_call' then
    update p2p_room_invitations set status = 'revoked', revoked_at = now(), updated_at = now()
      where church_call_id = p_room_id and status = 'active';
    insert into p2p_room_invitations (token_hash, church_call_id, created_by, expires_at)
      values (p_token_hash, p_room_id, p_created_by, p_expires_at)
      returning * into v_result;
  elsif p_room_type = 'family_worship' then
    update p2p_room_invitations set status = 'revoked', revoked_at = now(), updated_at = now()
      where family_worship_session_id = p_room_id and status = 'active';
    insert into p2p_room_invitations (token_hash, family_worship_session_id, created_by, expires_at)
      values (p_token_hash, p_room_id, p_created_by, p_expires_at)
      returning * into v_result;
  else
    raise exception 'invalid room_type: %', p_room_type;
  end if;
  return v_result;
end;
$$;

-- ── RLS ──────────────────────────────────────────────────────────────────────
-- No client INSERT/UPDATE/DELETE policy — creation goes through the
-- SECURITY DEFINER function above via the API's service-role connection
-- (matching this codebase's "API is the primary gate, RLS is the backstop"
-- convention used everywhere else). SELECT is a self-service convenience
-- (e.g. a future "my active links" list) — token-based resolution by OTHER
-- users happens through the API using the service-role client, which
-- bypasses RLS the same way every other route in this codebase already
-- does, and re-applies the real per-room-type authorization check in code.
alter table p2p_room_invitations enable row level security;

drop policy if exists "Creators see their own room invitations" on p2p_room_invitations;
create policy "Creators see their own room invitations" on p2p_room_invitations
  for select using (created_by = auth.uid() or p2p_is_admin());
